# Generated by Django 6.0.4 on 2026-04-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_classlevel_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_student_per_school',
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='name',
            field=models.CharField(choices=[('א', 'א'), ('ב', 'ב'), ('ג', 'ג'), ('ד', 'ד'), ('ה', 'ה'), ('ו', 'ו'), ('ז', 'ז'), ('ח', 'ח')], max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
