# Generated by Django 6.0.4 on 2026-04-26 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_studentevent_end_date_alter_studentevent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 26, 15, 54, 54, 789139, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studentevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 26, 15, 54, 54, 789139, tzinfo=datetime.timezone.utc)),
        ),
    ]
