# Generated by Django 6.0.6 on 2026-06-07 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_classsession_end_date_alter_classsession_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classsession",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="studentevent",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
