# Generated by Django 6.0.6 on 2026-06-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_agenda_to_student_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
