# Generated by Django 6.0.6 on 2026-06-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_classsession_summary_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentevent",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
