# Generated by Django 6.0.6 on 2026-06-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_lesson_plan_and_assignments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonclassassignment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
