# Generated by Django 6.0.6 on 2026-06-22 09:21

import core.models.document
import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_lessonclassassignment_id_alter_lessonplan_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "כללי"),
                            ("class", "כיתתי"),
                            ("student", "תלמיד"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=core.models.document.document_upload_path,
                        validators=[core.validators.validate_document_file],
                    ),
                ),
                (
                    "class_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.classlevel",
                    ),
                ),
                (
                    "counselor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.counselor",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.student",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["school", "category"],
                        name="core_docume_school__cb8e9c_idx",
                    ),
                    models.Index(
                        fields=["student"], name="core_docume_student_9f4ec1_idx"
                    ),
                    models.Index(
                        fields=["class_level", "class_number"],
                        name="core_docume_class_l_da55ca_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("category", "student"),
                            ("student__isnull", True),
                            _negated=True,
                        ),
                        name="document_student_required_for_student_category",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("category", "class"),
                            ("class_level__isnull", True),
                            _negated=True,
                        ),
                        name="document_class_level_required_for_class_category",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("category", "general"),
                            models.Q(
                                ("student__isnull", False),
                                ("class_level__isnull", False),
                                _connector="OR",
                            ),
                            _negated=True,
                        ),
                        name="document_general_must_have_no_relations",
                    ),
                ],
            },
        ),
    ]
