# Generated by Django 6.0.6 on 2026-06-23 07:40

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id_number",
            field=models.CharField(
                max_length=9,
                unique=True,
                validators=[core.validators.validate_id_number],
            ),
        ),
    ]
