# Generated by Django 6.0.6 on 2026-06-23 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_student_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'פתוח'), ('resolved', 'טופל')], default='open', max_length=20)),
                ('counselor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to='core.counselor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
