# Generated by Django 6.0.6 on 2026-06-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_support_request'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schoolyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_school_year'),
        ),
    ]
