# Generated by Django 6.0.6 on 2026-06-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_unique_active_school_year_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='parents_status',
            field=models.CharField(blank=True, choices=[('married', 'נשואים'), ('divorced', 'גרושים'), ('separated', 'פרודים'), ('single_parent', 'חד הוריות'), ('widowed', 'שכול'), ('other', 'אחר')], default='', max_length=20),
        ),
    ]
