# Generated by Django 6.0.6 on 2026-07-21 15:22

from django.db import migrations, models
from django.db.models import F


# Models that already had `created_at` before this migration; backfill their new
# `updated_at` from it so existing rows keep an accurate value instead of the
# migration-time now().
_MODELS_WITH_CREATED_AT = [
    "school",
    "counselor",
    "student",
    "studentenrollment",
    "studentevent",
    "lessonplan",
    "lessonclassassignment",
    "supportrequest",
]


def backfill_updated_at(apps, schema_editor):
    for model_name in _MODELS_WITH_CREATED_AT:
        model = apps.get_model("core", model_name)
        # .update() bypasses auto_now so we copy the real created_at value.
        model.objects.filter(created_at__isnull=False).update(updated_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_student_birth_date_student_external_care_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='classlevel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='counselor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lessonclassassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(backfill_updated_at, migrations.RunPython.noop),
    ]
