"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

import dj_database_url

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env before anything reads os.environ.
load_dotenv(BASE_DIR / ".env")

DEBUG = os.environ.get("DEBUG", "False") == "True"

# Deployment profile — one switch that derives sensible per-mode defaults for
# the database, media backend, email transport, and background scheduler. Every
# individual setting below still honours its own env-var override, so a specific
# install can deviate from its mode defaults. Feature code never reads this;
# all mode branching stays inside this settings module.
DEPLOYMENT_MODE = os.environ.get("DEPLOYMENT_MODE", "cloud").strip().lower()
_VALID_DEPLOYMENT_MODES = {"desktop", "cloud", "hybrid"}
if DEPLOYMENT_MODE not in _VALID_DEPLOYMENT_MODES:
    raise ImproperlyConfigured(
        "DEPLOYMENT_MODE must be one of "
        f"{sorted(_VALID_DEPLOYMENT_MODES)}, got {DEPLOYMENT_MODE!r}"
    )
# Desktop and hybrid run on-box (fully/partly local); cloud is centrally hosted.
IS_LOCAL_MODE = DEPLOYMENT_MODE in {"desktop", "hybrid"}

# Per-user runtime data directory (desktop/hybrid only). Every runtime-generated
# file — the SQLite DB, uploaded media, logs, backups, temp files — lives under
# one OS-standard, per-user root, kept outside the app bundle so reinstalling
# or upgrading the app never touches user data. Override the root explicitly
# via DESKTOP_DATA_DIR (e.g. to point at a scratch directory while testing).
# Cloud never uses this: DATA_DIR stays None and every path below falls back
# to its original BASE_DIR-relative default, so cloud behavior is unchanged.


def _default_desktop_data_dir() -> Path:
    app_name = "EduCare"
    if sys.platform == "win32":
        root = os.environ.get("APPDATA") or str(Path.home() / "AppData" / "Roaming")
    elif sys.platform == "darwin":
        root = str(Path.home() / "Library" / "Application Support")
    else:
        root = os.environ.get("XDG_DATA_HOME") or str(Path.home() / ".local" / "share")
    return Path(root) / app_name


DATA_DIR = None
if IS_LOCAL_MODE:
    DATA_DIR = Path(os.environ.get("DESKTOP_DATA_DIR") or _default_desktop_data_dir())
    for _subdir in ("media", "logs", "backups", "tmp"):
        (DATA_DIR / _subdir).mkdir(parents=True, exist_ok=True)

SECRET_KEY = os.environ.get("SECRET_KEY", "")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-dev-only-do-not-use-in-production"
    else:
        raise ImproperlyConfigured("SECRET_KEY environment variable is required when DEBUG=False")

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_yasg",
    "corsheaders",
    "django_apscheduler",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # Compresses API JSON (dashboard/calendar payloads) at the app level, so
    # responses are small on slow school connections regardless of whether
    # the hosting proxy compresses. Skips already-compressed bodies (e.g.
    # WhiteNoise's pre-gzipped statics, xlsx exports) and responses < 200
    # bytes; Django mitigates BREACH with random gzip padding.
    "django.middleware.gzip.GZipMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # Fail closed: any view that forgets to declare permission_classes
    # requires authentication instead of being public.
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    # Unhandled exceptions become a generic JSON 500 (full traceback goes to
    # the server log only) — see core/exception_handler.py.
    "EXCEPTION_HANDLER": "core.exception_handler.custom_exception_handler",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    # Env-overridable so local E2E runs (many logins/reloads from one IP)
    # can raise them; production uses these strict defaults.
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.environ.get("THROTTLE_ANON", "30/min"),
        "user": os.environ.get("THROTTLE_USER", "300/min"),
        "login": os.environ.get("THROTTLE_LOGIN", "5/min"),
        "token_refresh": os.environ.get("THROTTLE_REFRESH", "30/min"),
    },
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

# Path the httpOnly refresh cookie is scoped to. In production the frontend
# static site proxies /api/* to the backend, so the browser sees the auth
# endpoints under /api/token — the cookie path must match that proxied URL.
REFRESH_COOKIE_PATH = os.environ.get("REFRESH_COOKIE_PATH", "/token")

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Local modes are typically opened via either http://localhost:5173 or
# http://127.0.0.1:5173 (loopback) depending on how the dev server/bundled
# app is launched — allow both by default so neither breaks CORS. Cloud's
# default is unchanged.
_default_cors_origins = (
    "http://localhost:5173,http://127.0.0.1:5173" if IS_LOCAL_MODE else "http://localhost:5173"
)
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get("CORS_ALLOWED_ORIGINS", _default_cors_origins).split(",")
    if o.strip()
]
# Required so the browser sends/stores the httpOnly refresh cookie on /token/ calls.
CORS_ALLOW_CREDENTIALS = True

SWAGGER_SETTINGS = {
    "USE_SESSION_AUTH": False,
    "DEFAULT_INFO": "config.urls.api_info",
    "SECURITY_DEFINITIONS": {"Bearer": {"type": "apiKey", "name": "Authorization", "in": "header"}},
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DB engine follows the deployment mode via DATABASE_URL: cloud sets it to
# Neon PostgreSQL (keep ?sslmode=require). Desktop/hybrid, dev and pytest leave
# it unset and fall back to on-box SQLite — under DATA_DIR in local modes
# (see the per-user data directory block above), or BASE_DIR otherwise.
_default_sqlite_path = (DATA_DIR if DATA_DIR else BASE_DIR) / "db.sqlite3"
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{_default_sqlite_path}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "he"

TIME_ZONE = "Asia/Jerusalem"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise serves the collected static files (admin CSS/JS) straight from
# the app in production; media files use FileSystemStorage in dev and are
# switched to R2 below when R2_ACCOUNT_ID is set.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (user-uploaded documents). Local modes keep them under the
# per-user data directory (DATA_DIR); cloud keeps the original BASE_DIR path
# (irrelevant once R2 is configured, but still used as the local fallback).
MEDIA_URL = "/media/"
MEDIA_ROOT = (DATA_DIR / "media") if DATA_DIR else (BASE_DIR / "media")

# Backups (Step 5) and scratch/temp files. Only meaningful in local modes —
# cloud has no writable local disk to rely on, so these stay None there.
BACKUP_DIR = (DATA_DIR / "backups") if DATA_DIR else None
TEMP_DIR = (DATA_DIR / "tmp") if DATA_DIR else None

# Maximum upload size for documents (bytes). Override via env var.
DOCUMENT_MAX_UPLOAD_SIZE = int(os.environ.get("DOCUMENT_MAX_UPLOAD_SIZE", str(10 * 1024 * 1024)))

# Media/document storage adapter. Django's STORAGES["default"] IS the storage
# interface every FileField / `default_storage` call routes through, so swapping
# the backend here changes storage for all feature code without touching it.
# Cloud and hybrid use the Cloudflare R2 object store when configured; desktop
# always keeps documents on the local filesystem.
# PRIVATE bucket — files are only ever streamed through the permission-checked
# document endpoints, never served by direct URL.
_R2_ACCOUNT_ID = os.environ.get("R2_ACCOUNT_ID", "")
if _R2_ACCOUNT_ID and DEPLOYMENT_MODE != "desktop":
    INSTALLED_APPS += ["storages"]
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "endpoint_url": f"https://{_R2_ACCOUNT_ID}.r2.cloudflarestorage.com",
            "bucket_name": os.environ.get("R2_BUCKET_NAME", ""),
            "access_key": os.environ.get("R2_ACCESS_KEY_ID", ""),
            "secret_key": os.environ.get("R2_SECRET_ACCESS_KEY", ""),
            "region_name": "auto",
            "default_acl": None,
        },
    }

# Email
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
ADMIN_EMAIL = os.environ.get("ADMIN_EMAIL", EMAIL_HOST_USER)

# Transport: cloud sends real mail via SMTP; desktop/hybrid default to the
# console backend so the reminder job never blocks on missing SMTP creds.
# Providing EMAIL_HOST_USER (or EMAIL_BACKEND) opts a local install into SMTP.
_default_email_backend = (
    "django.core.mail.backends.smtp.EmailBackend"
    if DEPLOYMENT_MODE == "cloud" or EMAIL_HOST_USER
    else "django.core.mail.backends.console.EmailBackend"
)
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", _default_email_backend)

# Background reminder scheduler. core/apps.py only starts it under `runserver`
# (so pytest and gunicorn workers never do); this flag lets any mode force it
# off — e.g. RUN_SCHEDULER=0 on a replica — without touching feature code.
RUN_SCHEDULER = os.environ.get("RUN_SCHEDULER", "1") != "0"

# Security headers (always on; harmless in dev)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"

# HTTPS-only hardening — active only when actually served over TLS. Cloud is
# production behind HTTPS, so DEBUG=False there means "harden". Desktop/hybrid
# can also run with DEBUG=False (a packaged, production-like build) but are
# served over plain HTTP on the loopback interface (127.0.0.1) with no TLS
# terminator in front, so forcing HTTPS redirects/secure cookies there would
# break auth entirely — gate hardening on `not IS_LOCAL_MODE` too.
SECURE_COOKIES = not DEBUG and not IS_LOCAL_MODE
if SECURE_COOKIES:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "{levelname} {asctime} {name} {message}", "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "simple"},
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "django.security": {"level": "WARNING"},
    },
}

# Local modes also log to a rotating file under the per-user data directory,
# so logs survive/are inspectable outside the console (e.g. a windowed desktop
# app with no visible terminal).
if DATA_DIR:
    LOGGING["handlers"]["file"] = {
        "class": "logging.handlers.RotatingFileHandler",
        "filename": str(DATA_DIR / "logs" / "app.log"),
        "maxBytes": 5 * 1024 * 1024,
        "backupCount": 3,
        "formatter": "simple",
    }
    LOGGING["root"]["handlers"].append("file")
